name: 'Compute Config variables'

on:
  workflow_call:
    inputs:
      image-name-prefix:
        required: false
        type: string
        default: "ghcr.io/kitconcept/content"
      python-version:
        required: false
        type: string
        default: "3.13"
    outputs:
      backend:
        description: "Flag reporting if we should run the backend jobs"
        value: ${{ jobs.config.outputs.backend }}
      docs:
        description: "Flag reporting if we should run the docs jobs"
        value: ${{ jobs.config.outputs.docs }}
      base-tag:
        description: "Base tag to be used when creating container images"
        value: ${{ jobs.config.outputs.base-tag }}
      image-name-prefix:
        description: "Image name prefix for container images"
        value: ${{ inputs.image-name-prefix }}
      python-version:
        description: "Python version to be used"
        value: ${{ inputs.python-version }}

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      docs: ${{ steps.filter.outputs.docs }}
      base-tag: ${{ steps.vars.outputs.base-tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute several vars needed for the CI
        id: vars
        run: |
          echo "base-tag=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            backend:
              - '.github/workflows/backend*'
              - 'src/**'
              - 'tests/**'
              - 'pyproject.toml'
            docs:
              - '.readthedocs.yaml'
              - 'docs/**'
              - '.github/workflows/docs.yaml'

      - name: Test vars
        run: |
          echo "base-tag: ${{ steps.vars.outputs.BASE_TAG }}"
          echo "ref-name: ${{ github.ref_name }}"
          echo 'Paths - backend: ${{ steps.filter.outputs.backend }}'
          echo 'Paths - docs: ${{ steps.filter.outputs.docs }}'
