name: Publish new image to GHCR.io

on:
  workflow_call:
    inputs:
      base-tag:
        required: true
        type: string
      image-name-prefix:
        required: true
        type: string
      image-name-suffix:
        required: true
        type: string
      python-version:
        required: true
        type: string
      working-directory:
        required: false
        type: string
        default: .

jobs:

  docker:
    name: "Build and publish Container Image"
    if: ${{ github.event_name != 'pull_request' }}
    uses: plone/meta/.github/workflows/container-image-build-push.yml@2.x
    permissions:
      contents: read
      packages: write
    with:
      base-tag: ${{ inputs.base-tag }}
      image-name-prefix: ${{ inputs.image-name-prefix }}
      image-name-suffix: ${{ inputs.image-name-suffix }}
      working-directory: ${{ inputs.working-directory }}
      push: ${{ github.event_name != 'pull_request' }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}