debug = false

[sync]
klass = "kitconcept.contentsync.sync.person.PersonSyncer"
item_converter = "kitconcept.contentsync.converters.keycloak.KeycloakPersonConverter"

[src]
type="keycloak"
server_url="http://localhost:8180"
realm_name="plone"
client_id="plone-admin"
client_secret_key="12345678"
verify=false

[dst]
type="plone"
site_url="http://localhost:8080/Plone"
api_url="http://localhost:8080/Plone/++api++"
base_folder = "/"
username="admin"
password="admin"
